'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
'''Aufgabe                  '''
